//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AharHighLevel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Childeren = new HashSet<Form>();
            this.Parameters = new HashSet<Parameter>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> csd { get; set; }
        public string title { get; set; }
        public Nullable<int> parentId { get; set; }
    
        public virtual ICollection<Form> Childeren { get; set; }
        public virtual Form Parent { get; set; }
        public virtual ICollection<Parameter> Parameters { get; set; }
    }
}
