//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AharHighLevel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int id { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<bool> readOnly { get; set; }
        public string label { get; set; }
        public string unit { get; set; }
        public Nullable<bool> changeInRunMode { get; set; }
        public string value { get; set; }
        public Nullable<int> packetNumber { get; set; }
        public Nullable<int> packetIndex { get; set; }
        public Nullable<int> packetBitIndex { get; set; }
        public Nullable<decimal> Resolution { get; set; }
        public Nullable<bool> hasMinMax { get; set; }
        public string min { get; set; }
        public string max { get; set; }
        public Nullable<int> formId { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
